### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by chuuster** [chuuster/thesana#2]
Hey Liz, I've deployed to Heroku my app, up to user auth. There are still a few issues that I figured out yet though: 
- [x] logo image not rendered--code need to be rewritten using image_url helper method 
- [x] First click of "Demo User" button sometimes doesn't work, or lead to a "flickering" of error messages before redirecting to home page 
- [x] First click of "Logout" button sometimes doesn't work

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
 * You also need a splash page `/` that is styled to complete/close this issue
 * When I open the dev tool it messes up the styling on your page
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

Good job. Address the above unchecked items/comments, and then I can close the issue.

**Comment by chuuster** [comment]
Hey Liz, I've made the changes related to the unchecked boxes. Let me know if anything is missing. Thanks!

**Comment by eshoule** [comment]
Good job!
